- id: poetry-tag-checker
  name: Poetry git tag checker
  description: Enforce pyproject.toml version to be greater than the latest git tag through Poetry.
  entry: poetry-tag-checker
  language: script
  files: 'pyproject.toml'

