#!/usr/bin/env bash

POETRY_VERSION=$(poetry version -s)
LAST_GIT_TAG=$(git describe --tags --abbrev=0 2> /dev/null | cut -c2-)

if [[ -z "$LAST_GIT_TAG" ]]; then
  echo "No tag yet"
  exit 0
fi

if [[ $POETRY_VERSION > $LAST_GIT_TAG ]]; then
  exit 0
fi

poetry version $LAST_GIT_TAG > /dev/null
poetry version patch
exit 1

